In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

file_path = './TinhHuyenXa2021.xlsx'
df = pd.read_excel(file_path)

In [21]:
columns_to_drop = ['Tên Tiếng Anh','Cấp']

df = df.drop(columns_to_drop, axis=1)

In [23]:
df['Ward/Commune'] = df['Ward/Commune'].str.replace(r"^(Xã |Phường |Thị trấn )", "", regex=True)
df['District'] = df['District'].str.replace(r"^(Quận |Huyện |Thị xã |Thành phố )", "", regex=True)
df['Province'] = df['Province'].str.replace(r"^(Tỉnh |Thành phố )", "", regex=True)

In [27]:
file_name = "TinhHuyenXa.csv"
df.to_csv(file_name, index=False, encoding='utf-8-sig')

In [33]:
housing_data = pd.read_csv('vietnam_housing_dataset2.csv')
location_data = pd.read_csv('TinhHuyenXa.csv')

merged_data = pd.merge(housing_data, location_data, how='left', 
                       on=['Province', 'District', 'Ward/Commune'])

In [34]:
merged_data.head()

,Area,Frontage,Access Road,Floors,Bedrooms,Bathrooms,Price,Ward/Commune,District,Province,Ma_TP,Ma_QH,Ma_PX
0,84.0,NaN,NaN,4.0,NaN,NaN,8.60,Long Hưng,Văn Giang,Hưng Yên,33.0,326.0,12034.0
1,60.0,NaN,NaN,5.0,NaN,NaN,7.50,Nghĩa Trụ,Văn Giang,Hưng Yên,33.0,326.0,12031.0
2,90.0,6.0,13.0,5.0,NaN,NaN,8.90,Nghĩa Trụ,Văn Giang,Hưng Yên,33.0,326.0,12031.0
3,54.0,NaN,3.5,2.0,2.0,3.0,5.35,11,Gò Vấp,Hồ Chí Minh,79.0,764.0,26899.0
4,92.0,NaN,NaN,2.0,4.0,4.0,6.90,8,Gò Vấp,Hồ Chí Minh,79.0,764.0,26898.0

In [39]:
merged_data = merged_data.dropna(subset=['Ma_TP', 'Ma_QH', 'Ma_PX', 'Province'])

In [40]:
file_name = "vietnam_housing_dataset_final.csv"
merged_data.to_csv(file_name, index=False, encoding='utf-8-sig')

In [41]:
df = pd.read_csv('./vietnam_housing_dataset_final.csv')

In [43]:
numeric_columns = df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\trung\AppData\Local\Temp\ipykernel_7528\476495888.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [44]:
categorical_columns = df.select_dtypes(include=[object]).columns
for col in categorical_columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\trung\AppData\Local\Temp\ipykernel_7528\1124350905.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [45]:
columns_to_drop = ['Ward/Commune', 'District', 'Province']

df = df.drop(columns_to_drop, axis=1)

,Area,Frontage,Access Road,Floors,Bedrooms,Bathrooms,Price,Ward/Commune,District,Province,Ma_TP,Ma_QH,Ma_PX
0,84.0,4.5,6.0,4.0,3.0,3.0,8.60,Long Hưng,Văn Giang,Hưng Yên,33.0,326.0,12034.0
1,60.0,4.5,6.0,5.0,3.0,3.0,7.50,Nghĩa Trụ,Văn Giang,Hưng Yên,33.0,326.0,12031.0
2,90.0,6.0,13.0,5.0,3.0,3.0,8.90,Nghĩa Trụ,Văn Giang,Hưng Yên,33.0,326.0,12031.0
3,54.0,4.5,3.5,2.0,2.0,3.0,5.35,11,Gò Vấp,Hồ Chí Minh,79.0,764.0,26899.0
4,92.0,4.5,6.0,2.0,4.0,4.0,6.90,8,Gò Vấp,Hồ Chí Minh,79.0,764.0,26898.0

In [49]:
file_name = "vietnam_housing_dataset_final_2.csv"
df.to_csv(file_name, index=False, encoding='utf-8-sig')